[build]
  publish = "."
  functions = "functions"

# Edge Functions binding (site-wide)
[[edge_functions]]
  path = "/*"
  function = "headers"

# Bulletproof RSVP redirects with atomic safety
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
  force = true

[[redirects]]
  from = "/thank-you/"
  to = "/thank-you.html" 
  status = 200
  force = true

# Security & robots rules for admin pages
[[headers]]
  for = "/admin*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/dashboard*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Enterprise security headers (fallback to Edge Function)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"

# Alumni photo optimization
[[headers]]
  for = "/alumni-photos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Assets optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Forms processing with enhanced security
[form]
  settings = { spam_filter = true }

# Deploy contexts for different environments
[context.deploy-preview]
  environment = { NODE_ENV = "preview", DEBUG = "true" }

[context.branch-deploy]
  environment = { NODE_ENV = "staging" }

[context.production]
  environment = { NODE_ENV = "production", DEBUG = "false" }
