[build]
  publish = "."
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/event.ics"
  [headers.values]
    Content-Type = "text/calendar; charset=utf-8"

[[redirects]]
  from = "https://2025.dchs-football.org/*"
  to   = "https://dchs-football.org/2025/:splat"
  status = 301
  force  = true
